version: "3.3"
services:

  redis:
    image: redislabs/redistimeseries
    ports:
      - 6379:6379
    network_mode: host

  grafana:
    image: grafana-with-redis-plugin
    depends_on:
      - redis
    ports:
      - 3000:3000
    network_mode: host
    volumes:
      - ./grafana/:/etc/grafana/provisioning/

  python_script:
    image: python:alpine
    depends_on:
      - redis
    network_mode: host
    volumes:
      - ./script/:/etc/my-script/
    command: >
      sh -c "pip install -r /etc/my-script/requirements.txt &&
      python3 /etc/my-script/redis_insert.py"