# config file version
apiVersion: 1

# list of datasources that should be deleted from the database
deleteDatasources:
  - name: Redis
    orgId: 1

# list of datasources to insert/update depending
# whats available in the database
datasources:
  # <string, required> name of the datasource. Required
  - name: Redis
    # <string, required> datasource type. Required
    type: redis-datasource
    # <int> org id. will default to orgId 1 if not specified
    orgId: 1
    # <string> url
    url: redis://localhost:6379
    # <bool> allow users to edit datasources from the UI.
    editable: true
    # <int> splish splash
    poolSize: 5
